services:
  social_media:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["/app/entrypoint.sh"]
    volumes:
      - my_media:/vol/web/media
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.10-bookworm
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

  redis:
    image: redis:8.0-M03-alpine3.21
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  my_db:
  my_media:
  redis_data:
